### ISSUE TITLE
[Features request] field for the selection, local audio, extensive supports for the future maybe?

### ISSUE THREAD

**Issue by Ceynou** [Kartoffel0/Kindle2Anki#2]
First, thank you for the best script.
It's not particularly useful but it would be nice to have a field that holds the selection of your lookup, I think it's word in the WORDS database, on your card you can then highlight the selection in the sentence for a quicker reading.

I don't know if the time it takes to make cards is because of downloading audio from jpod but I think a great solution would be the local audio support like for the anki addon Yomichan local audio server.

The extensive supports are about just about the missing compatibilities, I have barely any programming knowledge so I can't tell how annoying implementation is.

Have a great day!

**Comment by Kartoffel0** [comment]
Funny enough the first version of this script did use Yomichan local audio server so it shouldn't be that hard to reimplement that. 
Kindle's auto detected lookup text is pretty hit or miss tho, it frequently includes the previous or next character surrounding the word you looked up so the result would be a little janky.

Sorry for the late reply btw, haven't had that much free time lately but I'll try to add both as soon as possible.

**Comment by Ceynou** [comment]
I appreciate it, thanks!
I saw the result was janky but it just to locate the word in the sentence with that little js script in anki's template

**Comment by Kartoffel0** [comment]
Can you ping me on TMW or dm me so you can test the local audio thingy? I don't know if they changed anything since the last time I used it and I really don't want to install it again. Kartoffel#7357

Got the term highlighting to work btw, works better than I expected ngl
![4](https://user-images.githubusercontent.com/99134182/188528256-17a8afac-aec1-4f1c-a7ce-05d6edf86b2b.JPG)
![1](https://user-images.githubusercontent.com/99134182/188528264-0f64d07f-c7a9-4377-9a4c-9b98ad9af3ad.JPG)
![2](https://user-images.githubusercontent.com/99134182/188528265-f6e0777e-a033-4b5b-8abd-9b143fb722f4.JPG)
![3](https://user-images.githubusercontent.com/99134182/188528266-bc099279-785e-4db8-9522-dd92a6f5f22b.JPG)
![fail](https://user-images.githubusercontent.com/99134182/188528262-6a6143cb-36a3-45b5-ab32-0f5d9ef93e91.JPG)
